### ISSUE TITLE
Summit presentation to the Lab - slides

### ISSUE THREAD

**Issue by tatianaxifara** [webblabb/summit#1]
[Summit_presentation.pptx](https://github.com/webblabb/summit/files/987971/Summit_presentation.pptx)

**Comment by gabrielgellner** [comment]
I think we should turn this into a markdown file that we add to the repo?

**Comment by gabrielgellner** [comment]
Also would it piss you off if I make a new repository that will be a bit more general? Something like: `WebbLabResources` ? Then summit can be part of it.

**Comment by ctwebb** [comment]
I thought Lindsay started something more general already?


________________________________

**Comment by gabrielgellner** [comment]
@lbeckjo does something general exist? I don't see it in the webblabb organization.

**Comment by lbeckjo** [comment]
Not on github. I had started a document with general information and code but haven't shared it yet because not complete. I think a general directory would be great, then I can add to it when I get the document I'm working on more complete

**Comment by gabrielgellner** [comment]
Okay. Will setup the new repository and get all of @tatianaxifara hard work moved over!

**Comment by gabrielgellner** [comment]
Okay I have things setup at https://github.com/webblabb/WebbLabResources
